In [1]:
import csv
import time
from tools.yahoo_api import get_key_stats

In [2]:
import pandas as pd
import plotly.plotly as py
import numpy as np
import collections
import json
from plotly.graph_objs import *
import matplotlib.pyplot as plt

In [3]:
def wait(seconds):
    time.sleep(seconds)

In [4]:
filename = 'sp500'
filename1= '2016-01-19'
filename2= '2016-08-23'

In [5]:
def write_stats(tickers, filename):
    print 'writing to file...'
    writer = csv.writer(open(filename, 'wb'))
    # write headers
    writer.writerow(tickers[tickers.keys()[0]].keys())
    for ticker in tickers:
        writer.writerow(tickers[ticker].values())
    print 'done'

In [6]:
def get_stats_for(tickers):
    for ticker in tickers.keys():
        print 'getting stats for ', ticker
        try:
            names, stats = get_key_stats(ticker)
            # print names, stats
            wait(0.2) # being a good citizen
            for name, stat in zip(names,stats):
                tickers[ticker][name] = stat
        # keep ticker stats only if all stats are valid
        except Exception, e:
            tickers.pop(ticker, None)
            print 'failed to save to dict ', str(e)
    print 'done'
    return tickers

In [7]:
def get_tickers_dict(filename):
    tickers = {}
    print 'filename', filename
    try:
        f = open(filename,'r').read()
        split_file = f.split('\n')
        for line in split_file:
            if line:
                split_line = line.split(',')
                tickers[split_line[0]] = {'name': split_line[1],'industry': split_line[2]}
        return tickers
    except Exception, e:
        print 'failed in get_tickers_dict', str(e)
    print 'done'

In [ ]:
tickers = get_tickers_dict(filename + '.txt')

In [ ]:
stats = get_stats_for(tickers)
# print stats

In [ ]:
write_stats(stats, filename + '.csv')

In [8]:
with open('tools/plotly_credentials.json', 'r') as creds:
        credentials = json.load(creds)

In [9]:
py.sign_in(credentials['plotly']['username'],
               credentials['plotly']['key'])

In [10]:
initial_state = pd.read_csv(filename1 + '.csv')
initial_state = initial_state.set_index('name')
print initial_state.head()

                  pb                industry    peg            mc
name
Allergan plc    1.61             Health Care   2.24  1.174600e+11
EOG Resources   2.64                  Energy -47.20  3.629000e+10
Campbell Soup  11.86        Consumer Staples   3.95  1.694000e+10
Qorvo           0.93  Information Technology   0.67  5.800000e+09
Nordstrom       6.29  Consumer Discretionary   2.92  8.830000e+09

In [11]:
final_state = pd.read_csv(filename2 + '.csv')
final_state = final_state.set_index('name')
print final_state.head()

                         mc                industry     pb         r   peg
name
Allergan plc   1.002600e+11             Health Care   1.40 -0.132218  1.34
EOG Resources  5.022000e+10                  Energy   4.16  0.501949 -0.20
Campbell Soup  1.866000e+10        Consumer Staples  11.30  0.123233  2.71
Qorvo          7.170000e+09  Information Technology   1.42  0.543951  0.83
Nordstrom      9.170000e+09  Consumer Discretionary   9.64  0.165682  3.18

In [12]:
returns = final_state[['r']]
print returns.head()

                      r
name
Allergan plc  -0.132218
EOG Resources  0.501949
Campbell Soup  0.123233
Qorvo          0.543951
Nordstrom      0.165682

In [13]:
grid_by = initial_state[['industry', 'pb', 'peg']]
print grid_by.head()

                             industry     pb    peg
name
Allergan plc              Health Care   1.61   2.24
EOG Resources                  Energy   2.64 -47.20
Campbell Soup        Consumer Staples  11.86   3.95
Qorvo          Information Technology   0.93   0.67
Nordstrom      Consumer Discretionary   6.29   2.92

In [14]:
complete = pd.concat([returns, grid_by], axis=1, join='inner').dropna()
print complete.head()
print complete.tail()

                      r                industry     pb    peg
name
Allergan plc  -0.132218             Health Care   1.61   2.24
EOG Resources  0.501949                  Energy   2.64 -47.20
Campbell Soup  0.123233        Consumer Staples  11.86   3.95
Qorvo          0.543951  Information Technology   0.93   0.67
Nordstrom      0.165682  Consumer Discretionary   6.29   2.92
                                  r                industry    pb   peg
name
Intuitive Surgical         0.250624             Health Care  4.80  1.96
Pfizer                     0.174892             Health Care  2.83  3.19
NIKE                       0.027921  Consumer Discretionary  7.71  2.24
Principal Financial Group  0.294218              Financials  1.12  3.40
Total System Services      0.081990  Information Technology  4.43  1.45

In [15]:
companiesNB = len(complete)
print companiesNB

451

In [16]:
xaxisMAX = 100;
yaxisMAX = 100;
step = 1;
zeros = np.zeros((100, 100))
z = pd.DataFrame(zeros)
count = pd.DataFrame(zeros)

In [17]:
complete = complete[(complete > 0).all(1)]

In [18]:
companiesNB = len(complete)
print companiesNB

366

In [55]:
xaxisMAX = 100;
yaxisMAX = 100;
step = 1;
zeros1 = np.zeros((100, 100))
zeros2 = np.zeros((100, 100))

z = pd.DataFrame(zeros1)
count = pd.DataFrame(zeros2)

In [56]:
for index, row in complete.iterrows():
    x = int(round(row['pb']))
    y = int(round(row['peg']))
    if (x < xaxisMAX and y < yaxisMAX):
        print index, x, y, z[x][y], count[x][y]
        z[x][y] = z[x][y] + row['r']
        count[x][y] = count[x][y] + 1.0
        print index, x, y, z[x][y], count[x][y]

Campbell Soup 12 4 0.0 0.0
Campbell Soup 12 4 0.123232775787 1.0
Qorvo 1 1 0.0 0.0
Qorvo 1 1 0.543951459246 1.0
Nordstrom 6 3 0.0 0.0
Nordstrom 6 3 0.165681696122 1.0
Molson Coors Brewing 2 7 0.0 0.0
Molson Coors Brewing 2 7 0.158388791211 1.0
Borg Warner 2 1 0.0 0.0
Borg Warner 2 1 0.144804211737 1.0
Waste Management 4 3 0.0 0.0
Waste Management 4 3 0.258031053055 1.0
Simon Property Group 12 2 0.0 0.0
Simon Property Group 12 2 0.165442384022 1.0
Goodyear Tire & Rub 2 1 0.144804211737 1.0
Goodyear Tire & Rub 2 1 0.219588993573 2.0
Genl Mills 7 3 0.0 0.0
Genl Mills 7 3 0.3008028936 1.0
Roper Technologies 3 2 0.0 0.0
Roper Technologies 3 2 0.0477039826793 1.0
Genl Electric 3 3 0.0 0.0
Genl Electric 3 3 0.113320442392 1.0
Genl Dynamics 4 1 0.0 0.0
Genl Dynamics 4 1 0.208292352779 1.0
Varian Medical Systems 4 3 0.258031053055 1.0
Varian Medical Systems 4 3 0.509940422244 2.0
General Motors 1 0 0.0 0.0
General Motors 1 0 0.112627788266 1.0
Mattel 3 26 0.0 0.0
Mattel 3 26 0.40885672903 1.0
Snap-On 4 2 0.0 0.0
Snap-On 4 2 0.00437089883641 1.0
Scripps Networks Interact 5 1 0.0 0.0
Scripps Networks Interact 5 1 0.168421940386 1.0
DENTSPLY International 3 3 0.113320442392 1.0
DENTSPLY International 3 3 0.184339539031 2.0
Macerich Co 2 3 0.0 0.0
Macerich Co 2 3 0.0989846698665 1.0
Johnson & Johnson 4 3 0.509940422244 2.0
Johnson & Johnson 4 3 0.760943822493 3.0
Xylem 3 2 0.0477039826793 1.0
Xylem 3 2 0.60403393894 2.0
Tyson Foods 2 1 0.219588993573 2.0
Tyson Foods 2 1 0.740605090562 3.0
Symantec Corp 2 3 0.0989846698665 1.0
Symantec Corp 2 3 0.680852003617 2.0
Cummins 2 2 0.0 0.0
Cummins 2 2 0.545087335428 1.0
Discovery Communications 3 2 0.60403393894 2.0
Discovery Communications 3 2 0.627298730593 3.0
CME Group 1 2 0.0 0.0
CME Group 1 2 0.247068718109 1.0
Comerica 1 1 0.543951459246 1.0
Comerica 1 1 0.878826279431 2.0
CMS Energy 3 3 0.184339539031 2.0
CMS Energy 3 3 0.372012272675 3.0
Humana 2 2 0.545087335428 1.0
Humana 2 2 0.645339322252 2.0
Priceline Group (The) 6 1 0.0 0.0
Priceline Group (The) 6 1 0.299652809502 1.0
HCP 2 4 0.0 0.0
HCP 2 4 0.140465335659 1.0
Frontier Communications 1 18 0.0 0.0
Frontier Communications 1 18 0.157285272562 1.0
Kellogg Co 9 5 0.0 0.0
Kellogg Co 9 5 0.176331694184 1.0
F5 Networks 5 1 0.168421940386 1.0
F5 Networks 5 1 0.504357769263 2.0
Ball Corp 9 3 0.0 0.0
Ball Corp 9 3 0.165752454052 1.0
O'Reilly Automotive 12 2 0.165442384022 1.0
O'Reilly Automotive 12 2 0.375294297893 2.0
BlackRock 2 2 0.645339322252 2.0
BlackRock 2 2 0.928595607066 3.0
Health Care REIT 2 3 0.680852003617 2.0
Health Care REIT 2 3 0.857856311413 3.0
Newfield Exploration 2 13 0.0 0.0
Newfield Exploration 2 13 0.876077067046 1.0
MasterCard 15 2 0.0 0.0
MasterCard 15 2 0.121462507304 1.0
CBRE Group 4 1 0.208292352779 1.0
CBRE Group 4 1 0.240155134007 2.0
Altria Group 39 2 0.0 0.0
Altria Group 39 2 0.158207522765 1.0
Northrop Grumman 6 3 0.165681696122 1.0
Northrop Grumman 6 3 0.323999755227 2.0
Micron Technology 1 24 0.0 0.0
Micron Technology 1 24 0.498148148148 1.0
CBS Corp 4 1 0.240155134007 2.0
CBS Corp 4 1 0.410105931593 3.0
Nasdaq OMX Group 2 2 0.928595607066 3.0
Nasdaq OMX Group 2 2 1.16718812782 4.0
Spectra Energy 2 5 0.0 0.0
Spectra Energy 2 5 0.539104810787 1.0
Morgan Stanley 1 1 0.878826279431 2.0
Morgan Stanley 1 1 1.07018492702 3.0
TJX Companies 10 2 0.0 0.0
TJX Companies 10 2 0.166006021297 1.0
Amgen 4 2 0.00437089883641 1.0
Amgen 4 2 0.17949593561 2.0
Facebook Cl 6 1 0.299652809502 1.0
Facebook Cl 6 1 0.605237497607 2.0
Costco Wholesale 6 3 0.323999755227 2.0
Costco Wholesale 6 3 0.445568693997 3.0
Dr. Pepper Snapple Group 8 3 0.0 0.0
Dr. Pepper Snapple Group 8 3 0.0424852384113 1.0
Dover Corp 2 3 0.857856311413 3.0
Dover Corp 2 3 1.26954276047 4.0
Dow Chemical 2 2 1.16718812782 4.0
Dow Chemical 2 2 1.46902548559 5.0
Microsoft Corp 5 2 0.0 0.0
Microsoft Corp 5 2 0.168500708831 1.0
Corning 1 8 0.0 0.0
Corning 1 8 0.381407023865 1.0
Schwab(Charles)Corp 3 1 0.0 0.0
Schwab(Charles)Corp 3 1 0.156020510738 1.0
Boston Scientific 4 1 0.410105931593 3.0
Boston Scientific 4 1 0.782331315771 4.0
Genl Growth Properties 3 2 0.627298730593 3.0
Genl Growth Properties 3 2 0.746627881366 4.0
Freeport-McMoRan 0 1 0.0 0.0
Freeport-McMoRan 0 1 2.02525252525 1.0
United Parcel Service 41 2 0.0 0.0
United Parcel Service 41 2 0.239059699513 1.0
Whirlpool Corp 2 1 0.740605090562 3.0
Whirlpool Corp 2 1 1.22219799322 4.0
Bed Bath & Beyond 3 2 0.746627881366 4.0
Bed Bath & Beyond 3 2 0.809657706651 5.0
Medtronic Plc 2 2 1.46902548559 5.0
Medtronic Plc 2 2 1.65813696781 6.0
Ford Motor 2 0 0.0 0.0
Ford Motor 2 0 0.0981442070241 1.0
Discover Financial Services 2 1 1.22219799322 4.0
Discover Financial Services 2 1 1.42913068778 5.0
CVS Health Corp 3 1 0.156020510738 1.0
CVS Health Corp 3 1 0.192652055663 2.0
Jacobs Engineering Group 1 2 0.247068718109 1.0
Jacobs Engineering Group 1 2 0.746519911837 2.0
Visa 6 2 0.0 0.0
Visa 6 2 0.138023937488 1.0
FMC Corp 2 3 1.26954276047 4.0
FMC Corp 2 3 1.66498423339 5.0
Avery Dennison Corp 5 2 0.168500708831 1.0
Avery Dennison Corp 5 2 0.508730463924 2.0
Tractor Supply 8 2 0.0 0.0
Tractor Supply 8 2 0.0284211682331 1.0
Allstate Corp 1 2 0.746519911837 2.0
Allstate Corp 1 2 0.928110039344 3.0
NetApp 2 1 1.42913068778 5.0
NetApp 2 1 2.08379109628 6.0
Lockheed Martin 23 3 0.0 0.0
Lockheed Martin 23 3 0.176867570205 1.0
3M Co 7 3 0.3008028936 1.0
3M Co 7 3 0.626117614562 2.0
Southern Co 2 4 0.140465335659 1.0
Southern Co 2 4 0.25521993303 2.0
Marsh & McLennan 4 2 0.17949593561 2.0
Marsh & McLennan 4 2 0.487838554155 3.0
WEC Energy Group 2 3 1.66498423339 5.0
WEC Energy Group 2 3 1.82300341405 6.0
Skyworks Solutions 4 0 0.0 0.0
Skyworks Solutions 4 0 0.237472810149 1.0
Adobe Systems 6 1 0.605237497607 2.0
Adobe Systems 6 1 0.739348284779 3.0
International Bus. Machines 8 1 0.0 0.0
International Bus. Machines 8 1 0.286949518405 1.0
Fidelity National Information Services 3 1 0.192652055663 2.0
Fidelity National Information Services 3 1 0.567009733973 3.0
Baxter International 2 3 1.82300341405 6.0
Baxter International 2 3 2.18792936867 7.0
Cardinal Health 4 1 0.782331315771 4.0
Cardinal Health 4 1 0.798551865911 5.0
Bank of America 1 1 1.07018492702 3.0
Bank of America 1 1 1.15590657684 4.0
Goldman Sachs Group 1 2 0.928110039344 3.0
Goldman Sachs Group 1 2 0.996120087049 4.0
ConAgra Foods 5 3 0.0 0.0
ConAgra Foods 5 3 0.210680532035 1.0
Legg Mason 1 1 1.15590657684 4.0
Legg Mason 1 1 1.25163246526 5.0
Laboratory Corp American Holdings 2 1 2.08379109628 6.0
Laboratory Corp American Holdings 2 1 2.33977217515 7.0
"Progressive Corp 2 2 1.65813696781 6.0
"Progressive Corp 2 2 1.77476644745 7.0
Hartford Finl Services Gp 1 1 1.25163246526 5.0
Hartford Finl Services Gp 1 1 1.28724918805 6.0
Celgene Corp 15 1 0.0 0.0
Celgene Corp 15 1 0.107000701175 1.0
Agilent Technologies 3 2 0.809657706651 5.0
Agilent Technologies 3 2 1.10225891088 6.0
SunTrust Banks 1 1 1.28724918805 6.0
SunTrust Banks 1 1 1.45187564414 7.0
St. Jude Medical 4 1 0.798551865911 5.0
St. Jude Medical 4 1 1.35237603468 6.0
Abbott Laboratories 3 2 1.10225891088 6.0
Abbott Laboratories 3 2 1.20144880542 7.0
Seagate Technology Plc 4 2 0.487838554155 3.0
Seagate Technology Plc 4 2 0.621803363259 4.0
Baker Hughes 1 3 0.0 0.0
Baker Hughes 1 3 0.318022382897 1.0
Cerner Corp 5 2 0.508730463924 2.0
Cerner Corp 5 2 0.654323674522 3.0
Pentair plc 2 1 2.33977217515 7.0
Pentair plc 2 1 2.84489155721 8.0
Pinnacle West Capital 2 3 2.18792936867 7.0
Pinnacle West Capital 2 3 2.40421477984 8.0
INVESCO Ltd 1 2 0.996120087049 4.0
INVESCO Ltd 1 2 1.08914703945 5.0
PNC Financial Services 1 2 1.08914703945 5.0
PNC Financial Services 1 2 1.10663727034 6.0
Boston Properties 3 3 0.372012272675 3.0
Boston Properties 3 3 0.568887746059 4.0
Google 4 2 0.621803363259 4.0
Google 4 2 0.729593847165 5.0
VF Corp 5 2 0.654323674522 3.0
VF Corp 5 2 0.874195605578 4.0
Amazon.com 22 5 0.0 0.0
Amazon.com 22 5 0.327200296867 1.0
Aon Plc 4 2 0.729593847165 5.0
Aon Plc 4 2 1.01480101055 6.0
Reynolds American 4 2 1.01480101055 6.0
Reynolds American 4 2 1.11563981636 7.0
Prudential Financial 1 1 1.45187564414 7.0
Prudential Financial 1 1 1.58767344777 8.0
Regions Financial 1 1 1.58767344777 8.0
Regions Financial 1 1 1.80146889198 9.0
Ralph Lauren Corp 2 2 1.77476644745 7.0
Ralph Lauren Corp 2 2 1.86261004209 8.0
Urban Outfitters 2 1 2.84489155721 8.0
Urban Outfitters 2 1 3.61641624352 9.0
Loews Corp 1 2 1.10663727034 6.0
Loews Corp 1 2 1.29331032543 7.0
Harris Corp 3 8 0.0 0.0
Harris Corp 3 8 0.0967418661684 1.0
Hormel Foods 5 2 0.874195605578 4.0
Hormel Foods 5 2 0.898356982382 5.0
Marathon Oil 0 1 2.02525252525 1.0
Marathon Oil 0 1 3.19600213014 2.0
Merck & Co 3 4 0.0 0.0
Merck & Co 3 4 0.259442800161 1.0
Interpublic GroupCompanies 5 2 0.898356982382 5.0
Interpublic GroupCompanies 5 2 0.982383372257 6.0
Red Hat 10 2 0.166006021297 1.0
Red Hat 10 2 0.211955771184 2.0
Tyco International 3 3 0.568887746059 4.0
Tyco International 3 3 1.08047232322 5.0
Amphenol Corp A 5 2 0.982383372257 6.0
Amphenol Corp A 5 2 1.34257504866 7.0
Ross Stores 9 2 0.0 0.0
Ross Stores 9 2 0.228913243923 1.0
Anadarko Petroleum 1 0 0.112627788266 1.0
Anadarko Petroleum 1 0 0.93326255412 2.0
Apache Corp 1 13 0.0 0.0
Apache Corp 1 13 0.574002745882 1.0
Air Products & Chemicals 3 1 0.567009733973 3.0
Air Products & Chemicals 3 1 0.882729415709 4.0
Kansas City Southern 2 2 1.86261004209 8.0
Kansas City Southern 2 2 2.37730566367 9.0
Sempra Energy 2 2 2.37730566367 9.0
Sempra Energy 2 2 2.54913944626 10.0
Whole Foods Market 3 3 1.08047232322 5.0
Whole Foods Market 3 3 1.12875442691 6.0
Wells Fargo 1 1 1.80146889198 9.0
Wells Fargo 1 1 1.82932653049 10.0
International Flavors/Fragr 6 3 0.445568693997 3.0
International Flavors/Fragr 6 3 0.673816766629 4.0
NVIDIA Corp 3 6 0.0 0.0
NVIDIA Corp 3 6 1.32052007388 1.0
Michael Kors Holdings 4 2 1.11563981636 7.0
Michael Kors Holdings 4 2 1.53566226714 8.0
Avago Technologies 7 0 0.0 0.0
Avago Technologies 7 0 0.486537343953 1.0
Raytheon Co 3 3 1.12875442691 6.0
Raytheon Co 3 3 1.30946135457 7.0
AFLAC 1 4 0.0 0.0
AFLAC 1 4 0.312780484398 1.0
Estee Lauder Co 9 2 0.228913243923 1.0
Estee Lauder Co 9 2 0.327744163185 2.0
Paychex 9 2 0.327744163185 2.0
Paychex 9 2 0.6365211149 3.0
Sherwin-Williams 23 1 0.0 0.0
Sherwin-Williams 23 1 0.227331461301 1.0
Consolidated Edison 2 6 0.0 0.0
Consolidated Edison 2 6 0.137162618642 1.0
Electronic Arts 7 1 0.0 0.0
Electronic Arts 7 1 0.221760373085 1.0
Computer Sciences 1 1 1.82932653049 10.0
Computer Sciences 1 1 2.47997297907 11.0
CSX Corp 2 3 2.40421477984 8.0
CSX Corp 2 3 2.67755136175 9.0
Torchmark Corp 2 2 2.54913944626 10.0
Torchmark Corp 2 2 2.74608232072 11.0
Edwards Lifesciences 7 2 0.0 0.0
Edwards Lifesciences 7 2 0.572195447082 1.0
Equinix 11 2 0.0 0.0
Equinix 11 2 0.267004800308 1.0
Eversource Energy 2 3 2.67755136175 9.0
Eversource Energy 2 3 2.74606895036 10.0
State Street Corp 1 3 0.318022382897 1.0
State Street Corp 1 3 0.581810379216 2.0
Murphy Oil 0 0 0.0 0.0
Murphy Oil 0 0 0.898149813161 1.0
Wyndham Worldwide 8 1 0.286949518405 1.0
Wyndham Worldwide 8 1 0.410999530452 2.0
Ecolab 4 2 1.53566226714 8.0
Ecolab 4 2 1.74149736481 9.0
Sealed Air 18 1 0.0 0.0
Sealed Air 18 1 0.200230061307 1.0
PVH Corp 1 2 1.29331032543 7.0
PVH Corp 1 2 1.94504521323 8.0
Quest Diagnostics 2 2 2.74608232072 11.0
Quest Diagnostics 2 2 3.04980354821 12.0
Nucor Corp 1 2 1.94504521323 8.0
Nucor Corp 1 2 2.3866477889 9.0
Expedia 6 1 0.739348284779 3.0
Expedia 6 1 0.82526417176 4.0
"Expeditors International 4 2 1.74149736481 9.0
"Expeditors International 4 2 1.943410764 10.0
Union Pacific 3 1 0.882729415709 4.0
Union Pacific 3 1 1.19608263533 5.0
E Trade Financial 1 1 2.47997297907 11.0
E Trade Financial 1 1 2.49609555126 12.0
Duke Energy 1 5 0.0 0.0
Duke Energy 1 5 0.148457967813 1.0
Ryder System 1 1 2.49609555126 12.0
Ryder System 1 1 2.89501300437 13.0
Best Buy 2 1 3.61641624352 9.0
Best Buy 2 1 4.18123325367 10.0
UnitedHealth Group 3 1 1.19608263533 5.0
UnitedHealth Group 3 1 1.46847034457 6.0
BB&T Corp 1 2 2.3866477889 9.0
BB&T Corp 1 2 2.5654508181 10.0
Omnicom Group 7 3 0.626117614562 2.0
Omnicom Group 7 3 0.871051386938 3.0
Coca-Cola Co 7 6 0.0 0.0
Coca-Cola Co 7 6 0.0622820701685 1.0
Vulcan Materials 3 5 0.0 0.0
Vulcan Materials 3 5 0.455551981563 1.0
Xilinx 5 4 0.0 0.0
Xilinx 5 4 0.28884005254 1.0
Lincoln National 1 1 2.89501300437 13.0
Lincoln National 1 1 3.06730431642 14.0
KeyCorp 1 1 3.06730431642 14.0
KeyCorp 1 1 3.16150134074 15.0
Illinois Tool Works 6 2 0.138023937488 1.0
Illinois Tool Works 6 2 0.620556741683 2.0
KLA-Tencor Corp 34 1 0.0 0.0
KLA-Tencor Corp 34 1 0.0827624645252 1.0
Stanley Black & Decker 2 1 4.18123325367 10.0
Stanley Black & Decker 2 1 4.474188821 11.0
Republic Services 2 4 0.25521993303 2.0
Republic Services 2 4 0.441747038071 3.0
Dollar General 4 1 1.35237603468 6.0
Dollar General 4 1 1.66049410188 7.0
Du Pont (E.I.) 4 2 1.943410764 10.0
Du Pont (E.I.) 4 2 2.29078808944 11.0
Walgreens Boots Alliance 3 1 1.46847034457 6.0
Walgreens Boots Alliance 3 1 1.50348433516 7.0
Target Corp 3 1 1.50348433516 7.0
Target Corp 3 1 1.55435937758 8.0
Huntington Bancshares 1 2 2.5654508181 10.0
Huntington Bancshares 1 2 2.59737064607 11.0
Biogen 6 1 0.82526417176 4.0
Biogen 6 1 1.00432658764 5.0
PG&E Corp 2 3 2.74606895036 10.0
PG&E Corp 2 3 2.97017972638 11.0
Akamai Technologies 3 2 1.20144880542 7.0
Akamai Technologies 3 2 1.38102629617 8.0
D.R.Horton 2 1 4.474188821 11.0
D.R.Horton 2 1 4.709347171 12.0
Macy's 3 4 0.259442800161 1.0
Macy's 3 4 0.311877103068 2.0
Martin Marietta Materials 2 2 3.04980354821 12.0
Martin Marietta Materials 2 2 3.69511501629 13.0
Intuit 23 2 0.0 0.0
Intuit 23 2 0.259532976812 1.0
SL Green Realty 1 2 2.59737064607 11.0
SL Green Realty 1 2 2.77375146376 12.0
Danaher Corp 3 2 1.38102629617 8.0
Danaher Corp 3 2 1.63360861682 9.0
McKesson Corp 4 1 1.66049410188 7.0
McKesson Corp 4 1 1.80184792124 8.0
NRG Energy 0 4 0.0 0.0
NRG Energy 0 4 0.276164807744 1.0
People's United Financial 1 2 2.77375146376 12.0
People's United Financial 1 2 2.89677834309 13.0
Ventas 2 3 2.97017972638 11.0
Ventas 2 3 3.33179753153 12.0
American Express 3 1 1.55435937758 8.0
American Express 3 1 1.61327073738 9.0
Exelon Corp 1 3 0.581810379216 2.0
Exelon Corp 1 3 0.868560027284 3.0
Apple 5 1 0.504357769263 2.0
Apple 5 1 0.649644799499 3.0
Western Union 6 1 1.00432658764 5.0
Western Union 6 1 1.3262831353 6.0
Weyerhaeuser Co 3 5 0.455551981563 1.0
Weyerhaeuser Co 3 5 0.720690066732 2.0
Vornado Realty Trust 3 3 1.30946135457 7.0
Vornado Realty Trust 3 3 1.45333458316 8.0
Unum Group 1 1 3.16150134074 15.0
Unum Group 1 1 3.40661542486 16.0
Host Hotels & Resorts 1 3 0.868560027284 3.0
Host Hotels & Resorts 1 3 1.33431616933 4.0
Hershey Co 21 3 0.0 0.0
Hershey Co 21 3 0.361006375254 1.0
Delphi Automotive Plc 8 1 0.410999530452 2.0
Delphi Automotive Plc 8 1 0.432386586718 3.0
Fifth Third Bancorp 1 2 2.89677834309 13.0
Fifth Third Bancorp 1 2 3.07143187145 14.0
Genuine Parts 4 4 0.0 0.0
Genuine Parts 4 4 0.347046525068 1.0
PattersonCompanies 3 2 1.63360861682 9.0
PattersonCompanies 3 2 1.81889027346 10.0
Harman International 2 1 4.709347171 12.0
Harman International 2 1 4.86007988029 13.0
Hasbro 6 2 0.620556741683 2.0
Hasbro 6 2 0.808339137345 3.0
Tenet Healthcare 3 1 1.61327073738 9.0
Tenet Healthcare 3 1 1.64159227008 10.0
Citrix Systems 5 1 0.649644799499 3.0
Citrix Systems 5 1 0.986257483017 4.0
Level 3 Communications 2 1 4.86007988029 13.0
Level 3 Communications 2 1 4.90549586173 14.0
Gap 4 3 0.760943822493 3.0
Gap 4 3 0.972417261465 4.0
PulteGroup 1 2 3.07143187145 14.0
PulteGroup 1 2 3.48478373496 15.0
Stryker Corp 4 2 2.29078808944 11.0
Stryker Corp 4 2 2.54025473457 12.0
Cimarex Energy 2 5 0.539104810787 1.0
Cimarex Energy 2 5 1.1794283072 2.0
DTE Energy 2 3 3.33179753153 12.0
DTE Energy 2 3 3.50089367786 13.0
Kimco Realty 2 3 3.50089367786 13.0
Kimco Realty 2 3 3.67596191094 14.0
Sysco Corp 4 3 0.972417261465 4.0
Sysco Corp 4 3 1.31023503502 5.0
American Electric Power 2 4 0.441747038071 3.0
American Electric Power 2 4 0.583549399283 4.0
Aetna 2 1 4.90549586173 14.0
Aetna 2 1 5.0530113599 15.0
EMC Corp 2 1 5.0530113599 15.0
EMC Corp 2 1 5.23888301015 16.0
Eastman Chemical 2 1 5.23888301015 16.0
Eastman Chemical 2 1 5.34913305846 17.0
Garmin Ltd 2 5 1.1794283072 2.0
Garmin Ltd 2 5 1.88375941043 3.0
Express Scripts Holding 3 1 1.64159227008 10.0
Express Scripts Holding 3 1 1.70749449718 11.0
Applied Materials 3 1 1.70749449718 11.0
Applied Materials 3 1 2.55236736142 12.0
Ameren Corp 1 3 1.33431616933 4.0
Ameren Corp 1 3 1.51527847607 5.0
Cintas Corp 5 2 1.34257504866 7.0
Cintas Corp 5 2 1.71419181513 8.0
Emerson Electric 3 3 1.45333458316 8.0
Emerson Electric 3 3 1.73998186352 9.0
FedEx Corp 2 1 5.34913305846 17.0
FedEx Corp 2 1 5.68018272459 18.0
News Corporation 1 2 3.48478373496 15.0
News Corporation 1 2 3.61652975841 16.0
Praxair 7 6 0.0622820701685 1.0
Praxair 7 6 0.327108519195 2.0
Procter & Gamble 3 3 1.73998186352 9.0
Procter & Gamble 3 3 1.90745859072 10.0
Parker-Hannifin 2 1 5.68018272459 18.0
Parker-Hannifin 2 1 6.11408066853 19.0
Equifax 5 2 1.71419181513 8.0
Equifax 5 2 1.98893025102 9.0
Citigroup 1 0 0.93326255412 2.0
Citigroup 1 0 1.05071948598 3.0
Mohawk Industries 3 1 2.55236736142 12.0
Mohawk Industries 3 1 2.85688557629 13.0
QUALCOMM 2 1 6.11408066853 19.0
QUALCOMM 2 1 6.50903602001 20.0
Xerox Corp 1 10 0.0 0.0
Xerox Corp 1 10 0.113155444402 1.0
Mosaic Co 1 2 3.61652975841 16.0
Mosaic Co 1 2 3.82052491627 17.0
Phillips 66 2 2 3.69511501629 13.0
Phillips 66 2 2 3.70792159233 14.0
Monsanto Co 11 2 0.267004800308 1.0
Monsanto Co 11 2 0.459557817808 2.0
Microchip Technology 4 2 2.54025473457 12.0
Microchip Technology 4 2 3.04520571692 13.0
ConocoPhillips 1 2 3.82052491627 17.0
ConocoPhillips 1 2 4.03121146322 18.0
Kinder Morgan 1 5 0.148457967813 1.0
Kinder Morgan 1 5 0.947552312353 2.0
Grainger (W.W.) 5 4 0.28884005254 1.0
Grainger (W.W.) 5 4 0.546933064261 2.0
Fiserv 7 2 0.572195447082 1.0
Fiserv 7 2 0.741557518406 2.0
Cabot Oil & Gas 4 5 0.0 0.0
Cabot Oil & Gas 4 5 0.587298778146 1.0
Capital One Financial 1 2 4.03121146322 18.0
Capital One Financial 1 2 4.15762918125 19.0
Coach 4 2 3.04520571692 13.0
Coach 4 2 3.36657448649 14.0
Public Svc Enterprises 2 9 0.0 0.0
Public Svc Enterprises 2 9 0.120264469356 1.0
Eaton Corp Plc 1 2 4.15762918125 19.0
Eaton Corp Plc 1 2 4.60477460032 20.0
Rockwell Collins 6 2 0.808339137345 3.0
Rockwell Collins 6 2 0.809155909715 4.0
Bard (C.R.) 9 2 0.6365211149 3.0
Bard (C.R.) 9 2 0.859123405228 4.0
CarMax 3 1 2.85688557629 13.0
CarMax 3 1 3.23139121135 14.0
Dollar Tree 4 2 3.36657448649 14.0
Dollar Tree 4 2 3.60873863322 15.0
Zimmer Biomet Holdings 2 1 6.50903602001 20.0
Zimmer Biomet Holdings 2 1 6.82234668725 21.0
Hess Corp 1 1 3.40661542486 16.0
Hess Corp 1 1 3.96560906214 17.0
Chubb Corp 1 1 3.96560906214 17.0
Chubb Corp 1 1 4.10287433156 18.0
Waters Corp 5 2 1.98893025102 9.0
Waters Corp 5 2 2.2747467196 10.0
Zoetis 17 2 0.0 0.0
Zoetis 17 2 0.191578227343 1.0
C.H. Robinson Worldwide 8 2 0.0284211682331 1.0
C.H. Robinson Worldwide 8 2 0.131581348601 2.0
Teradata Corp 3 2 1.81889027346 10.0
Teradata Corp 3 2 2.22832167895 11.0
Prologis 1 2 4.60477460032 20.0
Prologis 1 2 5.00911898219 21.0
Comcast Corp 3 1 3.23139121135 14.0
Comcast Corp 3 1 3.4522676783 15.0
McCormick & Co 6 3 0.673816766629 4.0
McCormick & Co 6 3 0.94436675895 5.0
Genworth Financial 0 1 3.19600213014 2.0
Genworth Financial 0 1 3.93217234291 3.0
Assurant 1 1 4.10287433156 18.0
Assurant 1 1 4.22168681189 19.0
Apartment Investment & Mgmt 4 2 3.60873863322 15.0
Apartment Investment & Mgmt 4 2 3.79417476787 16.0
Lowe'sCompanies 8 1 0.432386586718 3.0
Lowe'sCompanies 8 1 0.55410971132 4.0
American International Group 1 1 4.22168681189 19.0
American International Group 1 1 4.28515076191 20.0
Walt Disney Co 4 1 1.80184792124 8.0
Walt Disney Co 4 1 1.83055009463 9.0
PPG Indus 5 1 0.986257483017 4.0
PPG Indus 5 1 1.16156673985 5.0
Monster Beverage 6 2 0.809155909715 4.0
Monster Beverage 6 2 0.896334725935 5.0

In [57]:
z.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.898150,1.050719,0.098144,0.000000,0.237473,0.000000,0.000000,0.486537,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0
1,3.932172,5.294031,9.268226,5.105046,2.194412,1.651009,1.606180,0.221760,0.554110,0.580988,...,0,0,0,0,0,0,0,0,0,0
2,0.000000,6.231530,4.706333,4.063939,4.376763,3.194966,2.153809,0.741558,0.652250,0.859123,...,0,0,0,0,0,0,0,0,0,0
3,0.000000,2.334632,3.945085,2.082351,1.310235,0.539327,0.944367,0.871051,0.042485,0.165752,...,0,0,0,0,0,0,0,0,0,0
4,0.276165,0.428209,1.652918,0.418399,0.347047,0.546933,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0

In [58]:
count.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,1,3,1,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,3,25,34,22,12,8,7,1,4,1,...,0,0,0,0,0,0,0,0,0,0
2,0,23,18,19,20,13,8,2,5,4,...,0,0,0,0,0,0,0,0,0,0
3,0,8,16,11,5,2,5,3,1,1,...,0,0,0,0,0,0,0,0,0,0
4,1,2,9,3,1,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [59]:
z = np.divide(z, count)
z.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.898150,0.350240,0.098144,NaN,0.237473,NaN,NaN,0.486537,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.310724,0.211761,0.272595,0.232048,0.182868,0.206376,0.229454,0.221760,0.138527,0.580988,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,0.270936,0.261463,0.213892,0.218838,0.245767,0.269226,0.370779,0.130450,0.214781,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,0.291829,0.246568,0.189305,0.262047,0.269663,0.188873,0.290350,0.042485,0.165752,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.276165,0.214105,0.183658,0.139466,0.347047,0.273467,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
z[np.isnan(z)] = 0
z.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.898150,0.350240,0.098144,0.000000,0.237473,0.000000,0.000000,0.486537,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0
1,1.310724,0.211761,0.272595,0.232048,0.182868,0.206376,0.229454,0.221760,0.138527,0.580988,...,0,0,0,0,0,0,0,0,0,0
2,0.000000,0.270936,0.261463,0.213892,0.218838,0.245767,0.269226,0.370779,0.130450,0.214781,...,0,0,0,0,0,0,0,0,0,0
3,0.000000,0.291829,0.246568,0.189305,0.262047,0.269663,0.188873,0.290350,0.042485,0.165752,...,0,0,0,0,0,0,0,0,0,0
4,0.276165,0.214105,0.183658,0.139466,0.347047,0.273467,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0

In [48]:
data = [
    Contour(
        z=z.as_matrix()
    )
]

In [49]:
layout = Layout(
    title='Value Investing with Price to Book and Price to Earnings Growth',
    xaxis=dict(
        title='PB',
        range=[0, 2],
        titlefont=dict(
            family='Courier New, monospace',
            size=18,
            color='#7f7f7f'
        )
    ),
    yaxis=dict(
        title='PEG',
        range=[0, 2],
        titlefont=dict(
            family='Courier New, monospace',
            size=18,
            color='#7f7f7f'
        )
    )
)

In [50]:
fig = Figure(data=data, layout=layout)

In [51]:
py.iplot(fig, filename='compare ' + filename1 + ' and ' + filename2)